change ParseStatementOrDeclaration to emit the 'missing ;' with ExpectAndConsume instead of custom diag logic.  This gets us an insertion hint and positions the ; at the end of the line instead of on the next token.  Before:
t.c:5:1: error: expected ';' after return statement
}
^

after:

t.c:4:11: error: expected ';' after return statement
  return 4
          ^
          ;

llvm-svn: 73315