Revert r68847. It breaks the build on non-Darwin targets, with this message from the assembler:
Error: unknown pseudo-op: `.debug_inlined'
llvm-svn: 68863