[BOLT] Fix unused-variable warnings
This patch fixes:

  bolt/lib/Core/DebugData.cpp:1669:20: error: unused variable
  'StrOffset' [-Werror,-Wunused-variable]

  bolt/lib/Core/DebugData.cpp:1676:18: error: unused variable
  'NewOffset' [-Werror,-Wunused-variable]