[BOLT] Fix an unused-variable warning
This patch fixes:

  bolt/lib/Core/DIEBuilder.cpp:468:18: error: unused variable 'Ref'
  [-Werror,-Wunused-variable]