evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit 7aebdfc4fcc4a2667f5d5c30ffbdc146f9b014d2.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'