Add an expect() statement within breakpoint_conditions() method which tests that the process status is indeed 'stopped' before invoking 'frame variable -t val' command to inspect the frame variable.  When I run the test suite, it sometimes emits an output like:
runCmd: frame variable -t val
runCmd failed!
error: you must be stopped in a valid stack frame to view frame variables.

The expect() statement inserted is to make sure that the process is stopped and
we have a valid frame.

llvm-svn: 120318